# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_id',
            new_name='stat',
        ),
    ]
