# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20181018_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='stat',
        ),
        migrations.AddField(
            model_name='groups',
            name='total',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
