# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20181019_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='dateadded',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='owner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='ownername',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='secret',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
