# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20181020_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Group',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='photos',
            name='group',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Photo_Group'),
        ),
    ]
